version: '3'

services:
  gainz-api:
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_CONTAINER_URL}
      # - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  gainzdb:
    ports:
      - 6500:5432
  pgadmin:
    ports:
      - 5050:80
  
