services:
    gainzdb:
        image: postgres:18.0
        container_name: gainzdb
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 6500:5432
        volumes:
            - postgres_data:/var/lib/postgresql #persistent data
            # - ./seed.pgsql:/docker-entrypoint-initdb.d/seed.sql
            - ../assets/exercises.json:/docker-entrypoint-initdb.d/exercises.json #library of exercises for database to read from
            - ../assets/items:/docker-entrypoint-initdb.d/items #library of assets for database to read from
            - ../assets/items.json:/docker-entrypoint-initdb.d/items.json #library of items for database to read from
        healthcheck:
            test:
                ["CMD", "pg_isready", "-h", "gainzdb", "-U", "${POSTGRES_USER}"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        networks:
            - no_api_network

    # pgadmin:
    #   image: dpage/pgadmin4
    #   container_name: pgadmin4
    #   restart: always
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #     PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    #   ports:
    #     - "5050:80"
    #   depends_on:
    #     - gainzdb
    #   healthcheck:
    #     test: ["CMD", "pg_isready", "-U", "postgres", "-d", "gainzdb"]
    #     interval: 1m30s
    #     timeout: 30s
    #     retries: 5
    #     start_period: 30s
    #   networks:
    #     - no_api_network

volumes:
    postgres_data:
        driver: local

networks:
    no_api_network:
